<?php

/**
 * Implements hook_appstore_stores_info
 *
 * Add the bellcom_apps server
 */
function bellcom_apps_apps_servers_info() {
  $profile = variable_get('install_profile', 'standard');
  $info =  drupal_parse_info_file(drupal_get_path('profile', $profile) . '/' . $profile . '.info');
  return array(
    'bellcom' => array(
      'title' => 'Bellcom',
      'description' => "Apps from Bellcom",
      'manifest' => 'http://apps.bellcom.dk/app/query/production',
      'profile' => $profile,
      'profile_version' => isset($info['version']) ? $info['version'] : '7.x-1.x',
      'server_name' => $_SERVER['SERVER_NAME'],
      'server_ip' => $_SERVER['SERVER_ADDR'],
    ),
  );
}

/**
 * Implements hook_init()
 * 
 * Add a message if this is the levelten apps page.
 */
function bellcom_apps_init() {
  if ($_GET['q'] == 'admin/apps/bellcom') {
   
    apps_include('manifest'); 
    $server = apps_servers('bellcom');
    // Create args array for substitutions
    $manifest = apps_manifest($server);
    if (isset($manifest['message']) && $manifest['message'] != '') {
      foreach($server as $key => $value) {
        $args['!' . $key] = $value;
      }
      echo format_string($manifest['message']);
      die;
      drupal_set_message(format_string($manifest['message'], $args));
    }
  }
}
