name = OS2Forms frontend server
description = A Drupal distro for advanced webforms in Danish Municipalities
machine_name = os2forms_frontend_app
version =1.0 
downloadable = os2forms_frontend_app 7.x-1.0
author = Bellcom
author_url = http://www.bellcom.com
screenshots[] = os2forms.png
logo = os2froms_icon.png

dependencies[i18n] = i18n 7.x-2.0
dependencies[variable] = variable 7.x-2.5
dependencies[entity] = entity 7.x-1.6
dependencies[i18n_string] = i18n_string 7.x 1.13
dependencies[views] = views 7.x-3.11
dependencies[ctools] = ctools 7.x-1.7
dependencies[pathauto] = pathauto 7.x-1.2
dependencies[l10n_update] = l10n_update 7.x-2.0
dependencies[token] =  token 7.x-1.6
dependencies[services] = services 7.x-3.12
dependencies[webform_service] = webform_service 7.x-3.x-dev
dependencies[services_basic_auth] = services_basic_auth 7.x-1.3
dependencies[webform] = webform 7.x-4.10
dependencies[uuid] = uuid 7.x-1.0-beta1
dependencies[features] = features 7.x-1.0
dependencies[node_export] = node_export 7.x-3.0
dependencies[webform_submission_uuid] = webform_submission_uuid 7.x-1.x-dev
dependencies[libraries] = libraries 7.x-2.2

downloadables[os2forms_frontend_app 7.x-1.0] =https://github.com/OS2Forms/OS2forms-1.0/blob/master/os2forms_frontend_app.zip?raw=true
downloadables[i18n 7.x-1.13] = http://ftp.drupal.org/files/projects/i18n-7.x-1.13.tar.gz
downloadables[variable 7.x-2.5] = http://ftp.drupal.org/files/projects/variable-7.x-2.5.tar.gz
downloadables[entity 7.x-1.6] = http://ftp.drupal.org/files/projects/entity-7.x-1.6.tar.gz
downloadables[views 7.x-3.11] = http://ftp.drupal.org/files/projects/views-7.x-3.11.tar.gz
downloadables[l10n_update 7.x-2.0] = http://ftp.drupal.org/files/projects/l10n_update-7.x-2.0.tar.gz
downloadables[ctools 7.x-1.7] = http://ftp.drupal.org/files/projects/ctools-7.x-1.7.tar.gz
downloadables[token 7.x-1.6] = http://ftp.drupal.org/files/projects/token-7.x-1.6.tar.gz 
downloadables[services 7.x-3.12] = http://ftp.drupal.org/files/projects/services-7.x-3.12.tar.gz 
downloadables[i18n_string 7.x 1.13] = http://ftp.drupal.org/files/projects/i18n_string-7.x-3.13.tar.gz
downloadables[pathauto 7.x-1.2] = http://ftp.drupal.org/files/projects/pathauto-7.x-1.2.tar.gz
downloadables[webform_service 7.x-3.x-dev] = http://ftp.drupal.org/files/projects/webform_service-7.x-3.x-dev.tar.gz
downloadables[services_basic_auth 7.x-1.3] = http://ftp.drupal.org/files/projects/services_basic_auth-7.x-1.3.tar.gz 
downloadables[webform 7.x-4.10] = http://ftp.drupal.org/files/projects/webform-7.x-4.10.tar.gz
downloadables[wfm 7.x-1.x-dev] = http://ftp.drupal.org/files/projects/wfm-7.x-1.x-dev.tar.gz
downloadables[webform_validation 7.x-1.10] = http://ftp.drupal.org/files/projects/webform_validation-7.x-1.10.tar.gz
downloadables[features 7.x-1.0] = http://ftp.drupal.org/files/projects/features-7.x-1.0.tar.gz
downloadables[node_export 7.x-3.0] = http://ftp.drupal.org/files/projects/node_export-7.x-3.0.tar.gz
downloadables[uuid 7.x-1.0-beta1] = http://ftp.drupal.org/files/projects/uuid-7.x-1.0-beta1.tar.gz 
downloadables[webform_submission_uuid 7.x-1.x-dev] = http://ftp.drupal.org/files/projects/webform_submission_uuid-7.x-1.x-dev.tar.gz 
downloadables[libraries 7.x-2.2] = http://ftp.drupal.org/files/projects/libraries-7.x-2.2.tar.gz 